# This is an EDA (Exploratory Data Analysis) Script for Behaviour Logging of HiFPT Apps. The purpose is to observe the features, take some statistical number from the data.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data_path = "./data/behaviour_log.csv"
df = pd.read_csv(data_path, delimiter = ",")

C:\Users\HP\AppData\Local\Temp\ipykernel_28580\2409495462.py:6: DtypeWarning: Columns (0: campaign_ids, 1: utm_source, 2: segmentation.data.status, 3: segmentation.stable, 4: segmentation.platform) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_path, delimiter = ",")

In [ ]:
dropped_columns = ["id_data.vid", "process", "campaign_ids", "utm_source", 'ip_address', "segmentation.data.order_id",  "segmentation.data.transaction_id", "segmentation.data.status", "segmentation.session_id", "segmentation.data.report_id", "segmentation.stable", "segmentation.platform"]

In [3]:
df.drop(columns = dropped_columns, inplace = True)

## 1. Data Inspection

### 1a. Data records:

In [4]:
df.head()

,_id.$oid,device_id,customer_id,session_id,created_at.$date,timestamp,app_user_id,app_id,key,segmentation.segment,...,segmentation.mode,segmentation.$stable,segmentation.class_name,segmentation.duration,segmentation.error_des,segmentation.error_code,segmentation.screen_id,segmentation.type_res,segmentation.external_id,segmentation.error_msg
0,6a43fc3b0a23f209185526c1,35C1B931-2E90-46C4-B95D-71A4B2E81763,3268.0,E8E80173-34EC-488E-AC29-A164BF6050AA,2026-06-30T17:26:19.607Z,1782840377964,e762fd9d6af5215d70f01638040cd166af1a292e,68ac346aca32e453f5d66101,[CLY]_view,iOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6a43fc3b0a23f209185526c2,35C1B931-2E90-46C4-B95D-71A4B2E81763,3268.0,E8E80173-34EC-488E-AC29-A164BF6050AA,2026-06-30T17:26:19.605Z,1782840378456,e762fd9d6af5215d70f01638040cd166af1a292e,68ac346aca32e453f5d66101,[CLY]_orientation,NaN,...,portrait,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6a43fc3b0a23f209185526c3,35C1B931-2E90-46C4-B95D-71A4B2E81763,3268.0,E8E80173-34EC-488E-AC29-A164BF6050AA,2026-06-30T17:26:19.606Z,1782840378679,e762fd9d6af5215d70f01638040cd166af1a292e,68ac346aca32e453f5d66101,[CLY]_view,iOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6a4445f55914c9eb5aafc96b,064b3107e24ba3e3,NaN,a5c283b6-75a0-438a-8e58-60fd64f7c351,2026-06-30T22:40:53.057Z,1782859251069,7175482a3012f2306ff35991ccda828cde484879,68ac346aca32e453f5d66101,[CLY]_orientation,NaN,...,portrait,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6a4445f55914c9eb5aafc96c,064b3107e24ba3e3,NaN,a5c283b6-75a0-438a-8e58-60fd64f7c351,2026-06-30T22:40:53.060Z,1782859251080,7175482a3012f2306ff35991ccda828cde484879,68ac346aca32e453f5d66101,[CLY]_view,Android,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
df.tail(10)

,_id.$oid,device_id,customer_id,session_id,created_at.$date,timestamp,app_user_id,app_id,key,segmentation.segment,...,segmentation.mode,segmentation.$stable,segmentation.class_name,segmentation.duration,segmentation.error_des,segmentation.error_code,segmentation.screen_id,segmentation.type_res,segmentation.external_id,segmentation.error_msg
247046,6a4c84333b73f74d4804c67b,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:35.831Z,1783399474518,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,0.59,NaN,0.0,HomeVC,success,NaN,NaN
247047,6a4c84333b73f74d4804c67c,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:35.831Z,1783399474561,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,0.48,NaN,0.0,HomeVC,success,NaN,NaN
247048,6a4c84333b73f74d4804c67d,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:35.831Z,1783399474576,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,0.26,NaN,0.0,HomeVC,success,NaN,NaN
247049,6a4c84364c00fcea913966f5,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:38.178Z,1783399476820,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,2.89,NaN,0.0,HomeVC,success,NaN,NaN
247050,6a4c84364c00fcea913966f6,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:38.178Z,1783399476826,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,0.00,NaN,10405.0,HomeVC,application_error,NaN,Hiện tại yêu cầu của Quý khách không có thông tin
247051,6a4c84364c00fcea913966f7,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:38.178Z,1783399477245,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,3.32,NaN,0.0,HomeVC,success,NaN,NaN
247052,6a4c84370713cb0ae5d92b8a,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.666Z,1783399478895,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,[CLY]_view,iOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247053,6a4c84370713cb0ae5d92b8b,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.666Z,1783399478896,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,[CLY]_view,iOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247054,6a4c84370713cb0ae5d92b8c,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.664Z,1783399479024,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,0.12,NaN,0.0,ChooseContractVC,success,NaN,NaN
247055,6a4c8437598dfb494836aa3e,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.844Z,1783399478600,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,4.98,NaN,0.0,HomeVC,success,NaN,NaN

In [5]:
df.shape #shape í s a tuple of (#rows, #cols).
#df.size is number of total element records -> Rows x Cols.
#df.ndim -> Dimension of data. Table data is 2D.

(247056, 27)

### 1b. Data Overall Summary: 
- Statistics: including count, mean, std, min, interquantile range and maximum value. 
- info like non-null counts, dtypes of columns.

In [6]:
df.describe()

,customer_id,timestamp,segmentation.visit,segmentation.start,dur,segmentation.$stable,segmentation.duration,segmentation.error_code
count,2.058390e+05,2.470560e+05,42858.0,4020.0,247056.000000,71745.0,129368.000000,96076.000000
mean,5.306572e+06,1.783070e+12,1.0,1.0,12.632298,8.0,12.681386,2559.310931
std,2.374295e+06,1.747897e+08,0.0,0.0,633.197429,0.0,948.771865,6566.489300
min,1.990000e+02,1.782840e+12,1.0,1.0,0.000000,8.0,0.000000,-1017.000000
25%,2.004381e+06,1.782903e+12,1.0,1.0,0.000000,8.0,0.050000,0.000000
50%,6.789430e+06,1.782987e+12,1.0,1.0,0.000000,8.0,0.216000,0.000000
75%,7.345319e+06,1.783305e+12,1.0,1.0,0.000000,8.0,1.040000,0.000000
max,7.345725e+06,1.783399e+12,1.0,1.0,98982.000000,8.0,98958.300000,92005.000000

In [7]:
df.nunique() # This is for determine if a variable is continuous or discrete.

_id.$oid                    247056
device_id                      182
customer_id                    154
session_id                    1427
created_at.$date            139851
timestamp                   245465
app_user_id                    182
app_id                           1
key                              9
segmentation.segment             2
segmentation.visit               1
segmentation.name             2408
segmentation.start               1
dur                            757
id_data.id                  202350
id_data.cvid                 25093
id_data.peid                156171
segmentation.mode                2
segmentation.$stable             1
segmentation.class_name         91
segmentation.duration         6112
segmentation.error_des          49
segmentation.error_code         51
segmentation.screen_id         664
segmentation.type_res            5
segmentation.external_id       177
segmentation.error_msg          55
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 247056 entries, 0 to 247055
Data columns (total 27 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   _id.$oid                  247056 non-null  str
 1   device_id                 247056 non-null  str
 2   customer_id               205839 non-null  float64
 3   session_id                247056 non-null  str
 4   created_at.$date          247056 non-null  str
 5   timestamp                 247056 non-null  int64
 6   app_user_id               247056 non-null  str
 7   app_id                    247056 non-null  str
 8   key                       247056 non-null  str
 9   segmentation.segment      244744 non-null  str
 10  segmentation.visit        42858 non-null   float64
 11  segmentation.name         244700 non-null  str
 12  segmentation.start        4020 non-null    float64
 13  dur                       247056 non-null  int64
 14  id_data.id                247056 non-null  str
 15  id_data.cvid              160361 non-null  str
 16  id_data.peid              156910 non-null  str
 17  segmentation.mode         2058 non-null    str
 18  segmentation.$stable      71745 non-null   float64
 19  segmentation.class_name   16919 non-null   str
 20  segmentation.duration     129368 non-null  float64
 21  segmentation.error_des    6989 non-null    str
 22  segmentation.error_code   96076 non-null   float64
 23  segmentation.screen_id    155374 non-null  str
 24  segmentation.type_res     129368 non-null  str
 25  segmentation.external_id  4853 non-null    str
 26  segmentation.error_msg    10805 non-null   str
dtypes: float64(6), int64(2), str(19)
memory usage: 50.9 MB

### 1.c Data mising data info, count values and columns

In [55]:
na_series = df.isna().sum() #df.isna() returns pd.DataFrame: boolean matrix of original dataframe that the value is null will be N.A.
na_series[na_series > 0]

customer_id                  41217
ip_address                  247056
segmentation.segment          2312
segmentation.visit          204198
segmentation.name             2356
segmentation.start          243036
id_data.cvid                 86695
id_data.peid                 90146
id_data.vid                 247056
segmentation.mode           244998
segmentation.$stable        175311
segmentation.class_name     230137
segmentation.duration       117688
segmentation.error_des      240067
segmentation.error_code     150980
segmentation.screen_id       91682
segmentation.type_res       117688
segmentation.external_id    242203
segmentation.error_msg      236251
dtype: int64

In [68]:
df.columns

Index(['_id.$oid', 'device_id', 'customer_id', 'session_id',
       'created_at.$date', 'timestamp', 'app_user_id', 'app_id', 'key',
       'segmentation.segment', 'segmentation.visit', 'segmentation.name',
       'segmentation.start', 'dur', 'id_data.id', 'id_data.cvid',
       'id_data.peid', 'segmentation.mode', 'segmentation.$stable',
       'segmentation.class_name', 'segmentation.duration',
       'segmentation.error_des', 'segmentation.error_code',
       'segmentation.screen_id', 'segmentation.type_res',
       'segmentation.external_id', 'segmentation.error_msg'],
      dtype='str')

In [69]:
df.nunique() # Count distinct value in each column of a dataframe.

_id.$oid                    247056
device_id                      182
customer_id                    154
session_id                    1427
created_at.$date            139851
timestamp                   245465
app_user_id                    182
app_id                           1
key                              9
segmentation.segment             2
segmentation.visit               1
segmentation.name             2408
segmentation.start               1
dur                            757
id_data.id                  202350
id_data.cvid                 25093
id_data.peid                156171
segmentation.mode                2
segmentation.$stable             1
segmentation.class_name         91
segmentation.duration         6112
segmentation.error_des          49
segmentation.error_code         51
segmentation.screen_id         664
segmentation.type_res            5
segmentation.external_id       177
segmentation.error_msg          55
dtype: int64

In [ ]:
df["segmentation.type_res"].unique() # -> Return string array of values in the columns.

<StringArray>
[                nan, 'application error',           'success',
 'application_error',        'http_error',        'http error']
Length: 6, dtype: str

In [ ]:
df["key"].value_counts() # -> Return value counts for each value in column.

key
api_info             129368
[CLY]_view            86695
action                27844
[CLY]_orientation      2058
view_noti               417
process_data            402
end_session             254
search                   11
start_view                7
Name: count, dtype: int64

In [18]:
session_counts = df["session_id"].value_counts()
print(session_counts.index)

Index(['60f6a750-e80b-4503-8331-d08abcffae99',
       'f3feb6d0-3dd7-45e5-9113-d4af847a0b2f',
       'D01CBD18-09A0-460E-A863-62CDC42FE1ED',
       '9407DEFD-41B1-47A7-AC98-0F078C8DBA87',
       'A7F18FEC-985B-494C-97CA-A4099FA707F2',
       '9389E090-F53E-4DB5-B61A-B10497A1E355',
       '9f6da01a-34a4-44de-8ff5-7ec33849db6d',
       'b78b7ad9-3f9e-49e0-b55e-562714d51606',
       '742E78D6-A106-43DC-86D9-103E7BD0B40F',
       'F7D329EF-A43F-4584-B4D0-5B93DBF99C06',
       ...
       '832556FF-9C33-4041-ADAE-D36DFE5E9D5C',
       '578E10B7-F799-42A0-BE13-E7C39184775F',
       'b9a3bbb4-f098-450e-9ca3-5c5006e107c6',
       'a1b3d169-3a6e-4f00-8ced-3805e22e7de0',
       'f01d3e7a-e991-47bb-8e69-6adbba4967fa',
       'bd2145f1-985c-4266-8cce-12095718084d',
       '9844ea7d-fe3d-43ad-8197-dc0e393c5018',
       '70dc3f50-66ca-47e1-a8d7-797693786b24',
       '67be4e4e-bc26-4e9b-b84b-ccb3611d1132',
       '719ecc68-d0ca-4a23-a15f-41f9fc5d0567'],
      dtype='str', name='session_id', length=1427)

In [ ]:
sample_session = (
    df[df["session_id"] == df["session_id"].value_counts().index[0]] #Index is used to label and identify each element of the data -> In this case: the label for each value is the count of each session. Index[0] is the first session_id.
    .sort_values("timestamp")
)

print(f"Len of sample session {session_counts.index[0]} : {len(sample_session)}")

sample_session[
    [
        "session_id",
        "timestamp",
        "key",
        "segmentation.name",
        "segmentation.screen_id",
        "segmentation.type_res",
        "dur",
        "segmentation.duration"
    ]
].head(50)

Len of sample session 60f6a750-e80b-4503-8331-d08abcffae99 2432

,session_id,timestamp,key,segmentation.name,segmentation.screen_id,segmentation.type_res,dur,segmentation.duration
44501,60f6a750-e80b-4503-8331-d08abcffae99,1782895975573,[CLY]_view,android/home/payment,NaN,NaN,17,NaN
44502,60f6a750-e80b-4503-8331-d08abcffae99,1782895976982,[CLY]_view,SplashActivity,NaN,NaN,0,NaN
44503,60f6a750-e80b-4503-8331-d08abcffae99,1782895977011,[CLY]_view,SplashActivity,NaN,NaN,1,NaN
44507,60f6a750-e80b-4503-8331-d08abcffae99,1782895977013,[CLY]_view,MainAppActivity,NaN,NaN,0,NaN
44508,60f6a750-e80b-4503-8331-d08abcffae99,1782895977022,[CLY]_orientation,NaN,NaN,NaN,0,NaN
44509,60f6a750-e80b-4503-8331-d08abcffae99,1782895977221,[CLY]_view,MainAppActivity,NaN,NaN,0,NaN
44510,60f6a750-e80b-4503-8331-d08abcffae99,1782895977223,[CLY]_view,Splash,NaN,NaN,0,NaN
44511,60f6a750-e80b-4503-8331-d08abcffae99,1782895977240,api_info,https://hifpt-api-stag.fpt.vn/v123/customer-co...,Splash,success,0,0.080
44512,60f6a750-e80b-4503-8331-d08abcffae99,1782895977314,api_info,https://hifpt-api-stag.fpt.vn/v123/customer-co...,NaN,success,0,0.034
44504,60f6a750-e80b-4503-8331-d08abcffae99,1782895977444,api_info,https://hifpt-api-stag.fpt.vn/v123/auth/custom...,NaN,success,0,0.072
44505,60f6a750-e80b-4503-8331-d08abcffae99,1782895977492,[CLY]_view,Splash,NaN,NaN,0,NaN
44506,60f6a750-e80b-4503-8331-d08abcffae99,1782895977493,[CLY]_view,HOME,NaN,NaN,0,NaN
44513,60f6a750-e80b-4503-8331-d08abcffae99,1782895977613,[CLY]_view,HOME,NaN,NaN,0,NaN
44514,60f6a750-e80b-4503-8331-d08abcffae99,1782895977614,[CLY]_view,android/Home,NaN,NaN,0,NaN
44515,60f6a750-e80b-4503-8331-d08abcffae99,1782895977698,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,success,0,0.104
44522,60f6a750-e80b-4503-8331-d08abcffae99,1782895977703,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,success,0,0.109
44523,60f6a750-e80b-4503-8331-d08abcffae99,1782895977755,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,success,0,0.179
44524,60f6a750-e80b-4503-8331-d08abcffae99,1782895977783,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,application error,0,0.062
44516,60f6a750-e80b-4503-8331-d08abcffae99,1782895977843,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,application error,0,0.126
44517,60f6a750-e80b-4503-8331-d08abcffae99,1782895977851,api_info,https://hifpt-api-stag.fpt.vn/hi-tracking-api/...,android/Home,application error,0,0.045
44518,60f6a750-e80b-4503-8331-d08abcffae99,1782895977864,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,application error,0,0.065
44525,60f6a750-e80b-4503-8331-d08abcffae99,1782895977883,api_info,https://hifpt-api-stag.fpt.vn/hi-tracking-api/...,android/Home,application error,0,0.012
44526,60f6a750-e80b-4503-8331-d08abcffae99,1782895977898,api_info,https://hifpt-api-stag.fpt.vn/v123/customer/in...,android/Home,success,0,0.356
44527,60f6a750-e80b-4503-8331-d08abcffae99,1782895977913,api_info,https://hifpt-api-stag.fpt.vn/hi-tracking-api/...,android/Home,application error,0,0.012
44519,60f6a750-e80b-4503-8331-d08abcffae99,1782895977969,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,application error,0,0.084
44520,60f6a750-e80b-4503-8331-d08abcffae99,1782895977970,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,application error,0,0.052
44521,60f6a750-e80b-4503-8331-d08abcffae99,1782895978001,api_info,https://hifpt-api-stag.fpt.vn/hi-tracking-api/...,android/Home,application error,0,0.016
44528,60f6a750-e80b-4503-8331-d08abcffae99,1782895978036,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,success,0,0.044
44529,60f6a750-e80b-4503-8331-d08abcffae99,1782895978041,api_info,https://hifpt-api-stag.fpt.vn/hi-tracking-api/...,android/Home,application error,0,0.012
44530,60f6a750-e80b-4503-8331-d08abcffae99,1782895978112,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-loyalty-...,android/Home,success,0,0.055
44531,60f6a750-e80b-4503-8331-d08abcffae99,1782895978209,api_info,https://hifpt-api-stag.fpt.vn/v123/customer/ho...,android/Home,success,0,0.223
44532,60f6a750-e80b-4503-8331-d08abcffae99,1782895978241,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,application error,0,0.093
44533,60f6a750-e80b-4503-8331-d08abcffae99,1782895978284,api_info,https://hifpt-api-stag.fpt.vn/hi-tracking-api/...,android/Home,application error,0,0.014
44534,60f6a750-e80b-4503-8331-d08abcffae99,1782895978326,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,success,0,0.085
44535,60f6a750-e80b-4503-8331-d08abcffae99,1782895978339,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-loyalty-...,android/Home,success,0,0.071
44536,60f6a750-e80b-4503-8331-d08abcffae99,1782895979667,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,application error,0,1.884
44537,60f6a750-e80b-4503-8331-d08abcffae99,1782895979710,api_info,https://hifpt-api-stag.fpt.vn/hi-tracking-api/...,android/Home,application error,0,0.015
44538,60f6a750-e80b-4503-8331-d08abcffae99,1782895980374,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,success,0,2.514
44539,60f6a750-e80b-4503-8331-d08abcffae99,1782895980758,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-billing-...,android/Home,success,0,3.223
44540,60f6a750-e80b-4503-8331-d08abcffae99,1782895980954,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-billing-...,android/Home,success,0,2.569
44541,60f6a750-e80b-4503-8331-d08abcffae99,1782895984679,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,success,0,0.046
44542,60f6a750-e80b-4503-8331-d08abcffae99,1782895984831,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,android/Home,success,0,0.052
44543,60f6a750-e80b-4503-8331-d08abcffae99,1782895985411,action,banner,android/Home,NaN,0,NaN
44544,60f6a750-e80b-4503-8331-d08abcffae99,1782895985539,api_info,https://hifpt-api-stag.fpt.vn/v123/o2m-smart-l...,android/Home,success,0,0.087
44545,60f6a750-e80b-4503-8331-d08abcffae99,1782895985604,[CLY]_view,android/Home,NaN,NaN,8,NaN
44546,60f6a750-e80b-4503-8331-d08abcffae99,1782895985606,[CLY]_view,HiWebViewActivity,NaN,NaN,0,NaN
44547,60f6a750-e80b-4503-8331-d08abcffae99,1782895985826,api_info,https://hifpt-api-stag.fpt.vn/v123/hi-home-api...,HiWebViewActivity,application error,0,1.299
44548,60f6a750-e80b-4503-8331-d08abcffae99,1782895985906,api_info,https://hifpt-api-stag.fpt.vn/hi-tracking-api/...,HiWebViewActivity,application error,0,0.022
44549,60f6a750-e80b-4503-8331-d08abcffae99,1782895987782,[CLY]_view,HiWebViewActivity,NaN,NaN,2,NaN
44550,60f6a750-e80b-4503-8331-d08abcffae99,1782895987783,[CLY]_view,https://staging-hi.fpt.vn/web/game/spin-wheel/...,NaN,NaN,0,NaN

In [76]:
summary = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "non_null": df.notna().sum(),
    "missing": df.isna().sum(),
    "missing_pct": df.isna().mean().mul(100),
    "n_unique": df.nunique(dropna=True)
})

summary["unique_pct"] = (
    summary["n_unique"] / len(df) * 100
)

summary.sort_values("missing_pct", ascending=False)

,dtype,non_null,missing,missing_pct,n_unique,unique_pct
segmentation.mode,str,2058,244998,99.166990,2,0.000810
segmentation.start,float64,4020,243036,98.372839,1,0.000405
segmentation.external_id,str,4853,242203,98.035668,177,0.071644
segmentation.error_des,str,6989,240067,97.171087,49,0.019834
segmentation.error_msg,str,10805,236251,95.626498,55,0.022262
segmentation.class_name,str,16919,230137,93.151755,91,0.036834
segmentation.visit,float64,42858,204198,82.652516,1,0.000405
segmentation.$stable,float64,71745,175311,70.960025,1,0.000405
segmentation.error_code,float64,96076,150980,61.111651,51,0.020643
segmentation.duration,float64,129368,117688,47.636163,6112,2.473933
segmentation.type_res,str,129368,117688,47.636163,5,0.002024
segmentation.screen_id,str,155374,91682,37.109805,664,0.268765
id_data.peid,str,156910,90146,36.488084,156171,63.212794
id_data.cvid,str,160361,86695,35.091234,25093,10.156807
customer_id,float64,205839,41217,16.683262,154,0.062334
segmentation.name,str,244700,2356,0.953630,2408,0.974678
segmentation.segment,str,244744,2312,0.935820,2,0.000810
_id.$oid,str,247056,0,0.000000,247056,100.000000
device_id,str,247056,0,0.000000,182,0.073668
app_id,str,247056,0,0.000000,1,0.000405
key,str,247056,0,0.000000,9,0.003643
timestamp,int64,247056,0,0.000000,245465,99.356016
app_user_id,str,247056,0,0.000000,182,0.073668
created_at.$date,str,247056,0,0.000000,139851,56.607004
session_id,str,247056,0,0.000000,1427,0.577602
dur,int64,247056,0,0.000000,757,0.306408
id_data.id,str,247056,0,0.000000,202350,81.904507

In [ ]:
df.rename(
    {
        "_id.$oid": "record_id",
        "created_at.$date": 
    }
)

,_id.$oid,device_id,customer_id,session_id,created_at.$date,timestamp,app_user_id,app_id,key,segmentation.segment,...,segmentation.mode,segmentation.$stable,segmentation.class_name,segmentation.duration,segmentation.error_des,segmentation.error_code,segmentation.screen_id,segmentation.type_res,segmentation.external_id,segmentation.error_msg
0,6a43fc3b0a23f209185526c1,35C1B931-2E90-46C4-B95D-71A4B2E81763,3268.0,E8E80173-34EC-488E-AC29-A164BF6050AA,2026-06-30T17:26:19.607Z,1782840377964,e762fd9d6af5215d70f01638040cd166af1a292e,68ac346aca32e453f5d66101,[CLY]_view,iOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6a43fc3b0a23f209185526c2,35C1B931-2E90-46C4-B95D-71A4B2E81763,3268.0,E8E80173-34EC-488E-AC29-A164BF6050AA,2026-06-30T17:26:19.605Z,1782840378456,e762fd9d6af5215d70f01638040cd166af1a292e,68ac346aca32e453f5d66101,[CLY]_orientation,NaN,...,portrait,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6a43fc3b0a23f209185526c3,35C1B931-2E90-46C4-B95D-71A4B2E81763,3268.0,E8E80173-34EC-488E-AC29-A164BF6050AA,2026-06-30T17:26:19.606Z,1782840378679,e762fd9d6af5215d70f01638040cd166af1a292e,68ac346aca32e453f5d66101,[CLY]_view,iOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6a4445f55914c9eb5aafc96b,064b3107e24ba3e3,NaN,a5c283b6-75a0-438a-8e58-60fd64f7c351,2026-06-30T22:40:53.057Z,1782859251069,7175482a3012f2306ff35991ccda828cde484879,68ac346aca32e453f5d66101,[CLY]_orientation,NaN,...,portrait,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6a4445f55914c9eb5aafc96c,064b3107e24ba3e3,NaN,a5c283b6-75a0-438a-8e58-60fd64f7c351,2026-06-30T22:40:53.060Z,1782859251080,7175482a3012f2306ff35991ccda828cde484879,68ac346aca32e453f5d66101,[CLY]_view,Android,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247051,6a4c84364c00fcea913966f7,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:38.178Z,1783399477245,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,3.32,NaN,0.0,HomeVC,success,NaN,NaN
247052,6a4c84370713cb0ae5d92b8a,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.666Z,1783399478895,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,[CLY]_view,iOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247053,6a4c84370713cb0ae5d92b8b,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.666Z,1783399478896,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,[CLY]_view,iOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247054,6a4c84370713cb0ae5d92b8c,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.664Z,1783399479024,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,0.12,NaN,0.0,ChooseContractVC,success,NaN,NaN
247055,6a4c8437598dfb494836aa3e,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.844Z,1783399478600,873dd20942e004704604c091739e48bf3222b359,68ac346aca32e453f5d66101,api_info,iOS,...,NaN,NaN,NaN,4.98,NaN,0.0,HomeVC,success,NaN,NaN