# Clean and Standard Rows and Values in Data.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/cleaner_events_log.csv")

In [32]:
df.sort_values(by = "timestamp", ascending = True)

,record_id,utm_source,device_id,customer_id,session_id,created_at,timestamp,event_type,OS,segment_name,visit,duration,screen_name,segmentation.external_id
0,6a44668ba831463d3a03226b,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:55.014Z,1782867593723,View,Android,SplashActivity,1.0,0,NaN,NaN
1,6a44668ba831463d3a03226c,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:55.020Z,1782867593821,View,Android,SplashActivity,NaN,0,NaN,NaN
2,6a44668ba831463d3a03226d,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:55.014Z,1782867593823,View,Android,MainAppActivity,1.0,0,NaN,NaN
3,6a44668b7c74b952b232716e,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:55.921Z,1782867594297,View,Android,MainAppActivity,NaN,1,NaN,NaN
4,6a44668dfa0433f6e55bce9a,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:57.923Z,1782867594299,View,Android,Splash,1.0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114529,6a4c84325f185618f1c73dbc,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,NaN,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:34.672Z,1783399473232,View,iOS,OTPCreatePinVC,NaN,3,NaN,NaN
114530,6a4c84329cda512d2149787c,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:34.826Z,1783399473604,View,iOS,MainTabBarController,1.0,0,NaN,NaN
114531,6a4c84329cda512d2149787d,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:34.827Z,1783399473607,View,iOS,HomeVC,1.0,0,NaN,NaN
114532,6a4c84370713cb0ae5d92b8a,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.666Z,1783399478895,View,iOS,MainTabBarController,NaN,5,NaN,NaN
114533,6a4c84370713cb0ae5d92b8b,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.666Z,1783399478896,View,iOS,HomeVC,NaN,5,NaN,NaN

In [16]:
import json

segmentation_class_name = df["segment_name"].value_counts().index.to_list()
with open("data/segment_name.json", "w", encoding = 'utf-8') as f:
    json.dump(segmentation_class_name, f, indent = 4, ensure_ascii = False)

In [17]:
event_name = df["event_type"].value_counts().index.to_list()
with open("data/event_type.json", "w", encoding = 'utf-8') as f:
    json.dump(event_name, f, indent = 4, ensure_ascii = False)

In [18]:
screen_name = df["screen_name"].value_counts().index.to_list()
with open("data/screen_name.json", "w", encoding = 'utf-8') as f:
    json.dump(screen_name, f, indent = 4, ensure_ascii = False)

In [19]:
activity_duration = df["duration"].value_counts().index.to_list()
with open("data/activity_duration.json", "w", encoding = 'utf-8') as f:
    json.dump(activity_duration, f, indent = 4, ensure_ascii = False)

In [21]:
external = df["segmentation.external_id"].value_counts().index.to_list()
with open("data/segmentation_external.json", "w", encoding = 'utf-8') as f:
    json.dump(external, f, indent = 4, ensure_ascii = False)

In [31]:
df["event_type"] = df["event_type"].map({
    "[CLY]_view": "View",
    "action": "Action"
})

In [ ]:
print(len(df["event_type"] == "View"))
df[df["event_type"] == "View"].isna().sum()

114534

record_id                       0
utm_source                  84977
device_id                       0
customer_id                 13516
session_id                      0
created_at                      0
timestamp                       0
event_type                      0
OS                              0
segment_name                    0
visit                       43834
duration                        0
screen_name                 86690
segmentation.external_id    86690
dtype: int64

In [39]:
df

,record_id,utm_source,device_id,customer_id,session_id,created_at,timestamp,event_type,OS,segment_name,visit,duration,screen_name,segmentation.external_id
0,6a44668ba831463d3a03226b,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:55.014Z,1782867593723,View,Android,SplashActivity,1.0,0,NaN,NaN
1,6a44668ba831463d3a03226c,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:55.020Z,1782867593821,View,Android,SplashActivity,NaN,0,NaN,NaN
2,6a44668ba831463d3a03226d,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:55.014Z,1782867593823,View,Android,MainAppActivity,1.0,0,NaN,NaN
3,6a44668b7c74b952b232716e,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:55.921Z,1782867594297,View,Android,MainAppActivity,NaN,1,NaN,NaN
4,6a44668dfa0433f6e55bce9a,NaN,bf90fc3513bcad87,6793746.0,7eb5395b-ba4f-4113-975d-3a554211e235,2026-07-01T00:59:57.923Z,1782867594299,View,Android,Splash,1.0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114529,6a4c84325f185618f1c73dbc,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,NaN,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:34.672Z,1783399473232,View,iOS,OTPCreatePinVC,NaN,3,NaN,NaN
114530,6a4c84329cda512d2149787c,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:34.826Z,1783399473604,View,iOS,MainTabBarController,1.0,0,NaN,NaN
114531,6a4c84329cda512d2149787d,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:34.827Z,1783399473607,View,iOS,HomeVC,1.0,0,NaN,NaN
114532,6a4c84370713cb0ae5d92b8a,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.666Z,1783399478895,View,iOS,MainTabBarController,NaN,5,NaN,NaN
114533,6a4c84370713cb0ae5d92b8b,NaN,C49B7E38-3701-4747-A0F3-FE9AEEA8A30D,7345342.0,2457ADD5-8B15-4FB6-A1CE-24105BE8F339,2026-07-07T04:44:39.666Z,1783399478896,View,iOS,HomeVC,NaN,5,NaN,NaN

In [42]:
df.to_csv("data/final_clean_events.csv", index = False)